/**
 * @kizunasync/core engine: wire message types.
 * GENERATED by @kizunasync/protocol tools/generate-wire-types.ts: DO NOT EDIT.
 * Committed copy so the engine imports NO @kizunasync/protocol at runtime (one-way oracle/engine boundary).
 * Run `bun run generate` in packages/protocol; drift is caught by `check:gen`.
 */

/**
 * Normative concept: an opaque token encoding the last fully applied server sequence (P:mutations-and-column-masked-conflict-resolution). D-cursor-opaque-token selected a decimal high-water mark, optionally '~' plus ascending dot-separated holes. A continuation page prefixes '<start>:', the high-water of the checkpoint its transfer started from, and CHECKPOINT_EXPIRED checks that start; a checkpoint token carries none. The SQL pack emits no holes because its sequence numbers are commit-ordered, the refined reference oracle may emit them, and every codec accepts every form. Cursor '0' means bootstrap, and seq fields stay strictly decimal.
 * @status decided
 * @cites P:mutations-and-column-masked-conflict-resolution, SQL:pull-request-shape, DR:cursor-and-sequence-decimal-string-grammar
 */
export type TCursor = string

/**
 * Server-assigned sequence from one global sequence shared by all synced tables, drawn when the writing transaction commits (P:session-guarantees-and-exactly-once-effect mechanism 1; SQL:global-change-sequence). Decimal string on the wire (DR:cursor-and-sequence-decimal-string-grammar 'protocol state stored as TEXT everywhere'). Decimal seq and cursor token: dense from '1' per transcript except fencing cases (gaps by design).
 * @status proposed
 * @cites P:keyset-pagination-and-delivery-bound, SQL:global-change-sequence, DR:cursor-and-sequence-decimal-string-grammar
 */
export type TSeq = string

/**
 * Production wire values are RFC-4122 UUIDs; the corpus pins placeholder grammar: 00000000-0000-4000-8000-KKNNNNNNNNNN with kind codes a1 user · c1 client · e1 row pk · f1 mutation. Invariant I-6 requires registration in fixtures/identifiers.json.
 * @status proposed
 * @cites P:mutations-and-column-masked-conflict-resolution
 */
export type TUuid = string

/**
 * Logical timestamp grammar (C-8 schema-enforced): 2026-01-01T00:00:SS.000Z, SS = logical step seconds, strictly increasing per transcript for server-assigned fields.
 * @status proposed
 * @cites SQL:tombstones-deleted-at
 */
export type TIsoTimestamp = string

/**
 * Scalar column values only. C-4: JSON numbers are non-negative integers < 2^31; every int64-class value rides as a decimal string (DR:cursor-and-sequence-decimal-string-grammar); floats and exponents never appear in the corpus.
 * @status proposed
 * @cites P:mutations-and-column-masked-conflict-resolution, DR:cursor-and-sequence-decimal-string-grammar
 */
export type TColumnValue = string | number | boolean | null | (boolean | number | string)[]

/**
 * A { column: value } map whose key set IS the column mask (P:mutations-and-column-masked-conflict-resolution 'masked columns'). Invariant I-6 requires every column to exist in fixtures/domain.json.
 * @status proposed
 * @cites P:mutations-and-column-masked-conflict-resolution
 */
export type TColumnValues = Record<string, TColumnValue>

/**
 * @status normative
 * @cites P:mutations-and-column-masked-conflict-resolution
 */
export const EOp = {
  delete: 'delete',
  insert: 'insert',
  update: 'update',
} as const
export type TOp = (typeof EOp)[keyof typeof EOp]

/**
 * CHECKPOINT_EXPIRED: cursor predates oldest retained tombstone ⇒ client re-hydrates via keyset pagination. RESET_REQUIRED: client schema_version below the configured minimum ⇒ soft-block (P:schema-version-signalling).
 * @status normative
 * @cites P:cursor-monotonicity-rebase-and-atomic-checkpoints
 */
export const ESignalType = {
  CHECKPOINT_EXPIRED: 'CHECKPOINT_EXPIRED',
  RESET_REQUIRED: 'RESET_REQUIRED',
} as const
export type TSignalType = (typeof ESignalType)[keyof typeof ESignalType]

/**
 * Closed union (D-rejection-reasons). RLS_DENIED also covers a non-insert against an absent or caller-hidden row because an RLS-scoped server must not leak which case occurred (push/006). CONSTRAINT is a class-23 or class-22 error, or a P0001, raised while the mutation's row is applied, and rejects that mutation alone; DELETE_WINS rejects edits of tombstoned rows; SUPERSEDED means every masked column lost the hlc-mode comparison (conflict/003). COLUMN_DENIED refuses a mutation that writes a column the caller's role may not write; server_row carries the readable columns.
 * @status proposed
 * @cites P:verdict-completeness-transforms-and-conflict-rejection, P:mutations-and-column-masked-conflict-resolution, P:protocol-is-the-product-the-corpus-is-the-arbiter
 */
export const ERejectReason = {
  COLUMN_DENIED: 'COLUMN_DENIED',
  CONSTRAINT: 'CONSTRAINT',
  DELETE_WINS: 'DELETE_WINS',
  PRECONDITION: 'PRECONDITION',
  RLS_DENIED: 'RLS_DENIED',
  SUPERSEDED: 'SUPERSEDED',
} as const
export type TRejectReason = (typeof ERejectReason)[keyof typeof ERejectReason]

/**
 * @status normative
 * @cites P:mutations-and-column-masked-conflict-resolution
 */
export const EVerdictKind = {
  applied: 'applied',
  rejected: 'rejected',
} as const
export type TVerdictKind = (typeof EVerdictKind)[keyof typeof EVerdictKind]

/**
 * @status normative
 * @cites P:verdict-completeness-transforms-and-conflict-rejection
 */
export const EBatchOutcome = {
  aborted: 'aborted',
} as const
export type TBatchOutcome = (typeof EBatchOutcome)[keyof typeof EBatchOutcome]

/** EConflictMode */
export const EConflictMode = {
  arrival: 'arrival',
  hlc: 'hlc',
} as const
export type TConflictMode = (typeof EConflictMode)[keyof typeof EConflictMode]

/**
 * A bucket is {table, params}. Current transcripts use one owner-equality bucket {"table":"todos","params":{"owner_id":"<user uuid>"}}; that fixture choice does not narrow the schema.
 * @status proposed
 * @cites P:mutations-and-column-masked-conflict-resolution
 */
export type TBucket = {
  params: Record<string, boolean | number | string>
  table: string
}

/**
 * PostgREST RPC body for kizunasync.pull: top-level keys are SQL argument names. Client identity rides the optional client_id key (D-client-identity), with the Supabase Auth JWT session_id claim as the fallback when it is absent.
 * @status normative
 * @cites P:cursor-monotonicity-rebase-and-atomic-checkpoints, SQL:pull-request-shape
 */
export type TPullRequest = {
  buckets: ({ params: Record<string, boolean | number | string>; table: string })[]
  client_id?: string
  cursor: TCursor
  limit?: number
  schema_version: number
}

/**
 * Latest state only: Postgres-is-the-snapshot, no row-image oplog (P:cursor-monotonicity-rebase-and-atomic-checkpoints). Rows may carry attachment references as ordinary column values; attachment bytes never ride this channel (P:attachments-are-out-of-protocol-scope, AT:media-attachments). The current corpus domain has no attachment column.
 * @status normative
 * @cites P:cursor-monotonicity-rebase-and-atomic-checkpoints, P:keyset-pagination-and-delivery-bound
 */
export type TRowChange = {
  pk: TUuid
  row: TColumnValues
  seq: TSeq
  table: string
}

/**
 * Tombstone field set: (table, pk, seq, deleted_at), written by AFTER DELETE trigger and reaped past TTL; TTL interacts with checkpoint expiry.
 * @status normative
 * @cites P:mutations-and-column-masked-conflict-resolution, SQL:tombstones-table
 */
export type TTombstone = {
  deleted_at: TIsoTimestamp
  pk: TUuid
  seq: TSeq
  table: string
}

/**
 * Signal names are normative (P:cursor-monotonicity-rebase-and-atomic-checkpoints). D-signal-excludes-page-data ratified the exclusive shape enforced by invariant I-8: a non-null signal means empty rows and tombstones with has_more false.
 * @status normative
 * @cites P:cursor-monotonicity-rebase-and-atomic-checkpoints
 */
export type TSignal = { type: TSignalType } | null

/**
 * The pull response carries changed rows, tombstones, a new cursor, and typed signals (P:cursor-monotonicity-rebase-and-atomic-checkpoints). D-conflict-journal-visibility makes conflicts optional, omitted when empty; C-2 fixes the key order when present: conflicts, cursor, has_more, rows, signal, tombstones.
 * @status proposed
 * @cites P:cursor-monotonicity-rebase-and-atomic-checkpoints
 */
export type TPullResponse = {
  conflicts?: { column_name: string; conflict_mode: TConflictMode; loser_value: unknown; pk: TUuid; table: string; winner_mutation_id: TUuid; winner_seq: TSeq }[]
  cursor: TCursor
  has_more: boolean
  rows: TRowChange[]
  signal: TSignal
  tombstones: TTombstone[]
}

/**
 * The outbox unit: mutation_id, table, pk, op, masked columns, base_hint.
 * @status normative
 * @cites P:mutations-and-column-masked-conflict-resolution
 */
export type TMutation = {
  base_hint?: unknown
  columns: TColumnValues
  hlc?: string
  mutation_id: TUuid
  op: TOp
  pk: TUuid
  precondition?: TColumnValues
  table: string
  transforms?: Record<string, TTransform>
}

/**
 * Closed field-transform menu (D-field-transforms). increment.by is a signed integer: schema exception to C-4 (C-4 non-negative ints stay on column_values). JSON number when |n| < 2^31, else decimal string.
 * @status decided
 * @cites P:verdict-completeness-transforms-and-conflict-rejection
 */
export type TTransform = { by: number | string; op: 'increment' } | { op: 'arrayRemove' | 'arrayUnion'; values: (boolean | number | string)[] }

/**
 * Selected D-conflict-journal-visibility shape for one overwritten column. winner_seq is the changelog seq of the winning write, always one of the seqs in the delivered page; pk must already be present in rows.
 * @status decided
 * @cites P:cursor-monotonicity-rebase-and-atomic-checkpoints, P:session-guarantees-and-exactly-once-effect
 */
export type TConflict = {
  column_name: string
  conflict_mode: TConflictMode
  loser_value: unknown
  pk: TUuid
  table: string
  winner_mutation_id: TUuid
  winner_seq: TSeq
}

/**
 * One server transaction per batch; idempotent via mutation UUIDs (P:verdict-completeness-transforms-and-conflict-rejection). Batch and mutation key spellings are this schema.
 * @status proposed
 * @cites P:verdict-completeness-transforms-and-conflict-rejection, SQL:push-request-shape
 */
export type TPushBatch = {
  atomic: boolean
  mutations: TMutation[]
}

/**
 * PostgREST RPC body for kizunasync.push: top-level keys are SQL argument names. Client identity rides the optional client_id key (D-client-identity), with the Supabase Auth JWT session_id claim as the fallback when it is absent.
 * @status normative
 * @cites P:verdict-completeness-transforms-and-conflict-rejection, SQL:push-request-shape
 */
export type TPushRequest = {
  batch: { atomic: boolean; mutations: TMutation[] }
  client_id?: string
  last_mutation_id: TUuid | null
  schema_version: number
}

/**
 * applied ⇒ the client clears the outbox entry (P:verdict-completeness-transforms-and-conflict-rejection).
 * @status normative
 * @cites P:mutations-and-column-masked-conflict-resolution
 */
export type TVerdictApplied = {
  mutation_id: TUuid
  server_row?: TColumnValues
  verdict: typeof EVerdictKind.applied
}

/**
 * A rejected verdict drives a compensating revert to server_row plus a typed event (P:verdict-completeness-transforms-and-conflict-rejection).
 * @status normative
 * @cites P:mutations-and-column-masked-conflict-resolution, P:verdict-completeness-transforms-and-conflict-rejection
 */
export type TVerdictRejected = {
  mutation_id: TUuid
  reason: TRejectReason
  server_row: TColumnValues | null
  verdict: typeof EVerdictKind.rejected
}

/**
 * The union is normative: applied | rejected(reason, server_row) (P:mutations-and-column-masked-conflict-resolution Verdict, Realm compensating-writes lineage). D-verdict-correlation ratified dual correlation by request order and mutation_id, and invariant I-5 enforces the bijection for verdict responses.
 * @status normative
 * @cites P:mutations-and-column-masked-conflict-resolution, P:verdict-completeness-transforms-and-conflict-rejection
 */
export type TVerdict = TVerdictApplied | TVerdictRejected

/**
 * @status normative
 * @cites P:verdict-completeness-transforms-and-conflict-rejection
 */
export type TBatchAbort = {
  offender_mutation_id: TUuid
  outcome: typeof EBatchOutcome.aborted
  reason: TRejectReason
  server_row: TColumnValues | null
}

/**
 * kizunasync.push response (JSON:API / AIP-233 shape). A non-atomic batch and a successful atomic batch carry per-mutation verdicts under the correlation D-verdict-correlation ratified; an atomic rejection returns the D-atomic-batch-abort batch outcome; a stale schema_version returns the D-schema-version-handshake RESET_REQUIRED signal before any mutation runs.
 * @status normative
 * @cites P:mutations-and-column-masked-conflict-resolution, P:verdict-completeness-transforms-and-conflict-rejection
 */
export type TPushResponse = { verdicts: TVerdict[] } | { batch: TBatchAbort } | { signal: { type: TSignalType } }
