// MARK: - @kizunasync/utilities public surface

export { createCaptchaGate, type ICaptchaGate } from './captcha-gate'
export { messageOf } from './errors'
export { createQueryLog, type IQueryLog, type IQueryLogEntry, type TQueryOp } from './query-log'
export { createConnectivityGate, createGatedWakeup, createLiveSyncGate, type ILiveSyncGate } from './devtools'
export { accountKeyForUserId, createDemoAccounts, DEMO_PASSWORD, REGISTERED_UID_NAMES, type IDemoAccount, type TDemoAccountKey } from './demo-accounts'
export { EDIT_ALL_SUFFIX, isTodoArchived, isTodoEditable, isTodoMine, matchesTodoFilter, PREDEFINED_TODO_TITLES, predefinedTodoStamps, sortTodosMineFirst, TITLE_MAX_LENGTH, withEditAllSuffix, type TTodoStatusFilter } from './todo-board'
export { ARCHIVED_COLUMN, IMAGE_BUCKET, TODOS_TABLE, todosConfig, type TTodoDatabase, type TTodoRow } from './todo-schema'
export { createEngineEventLog, summarizeEngineEvent, type TEngineEventLogEntry } from './engine-events'
export { formatClockTime, formatRelativeTime } from './time'
export { forceServerConflict, type IConflictDrillRemote } from './conflict-drills'
export { wireLabControls, type ILabControls, type IWireLabControlsOptions } from './lab-controls'
export { decideAccountSwitch, EAccountSwitchDecisionKind, performAccountSwitch, recoverSession, type IAccountSwitchAuth, type IAccountSwitchOptions, type IAccountSwitchPorts, type ISwitchTarget, type TAccountSwitchDecision, type TAccountSwitchDecisionKind, type TRecoveredSession } from './account-switch'
export { IDENTITY_RECOVERED_MESSAGE, resetOnIdentityChange, type IResetOnIdentityChangeParams } from './identity-recovery'
