import type { IReferenceLibrary } from '../reference-registry'

// MARK: - JavaScript client reference tree

export const JAVASCRIPT: IReferenceLibrary = {
  id: 'javascript',
  title: 'JavaScript',
  packageName: 'kizunasync',
  description:
    'kizunasync, kizunasync/supabase, and kizunasync/web: createKizunaSync, the local query builder, sync controls, adapters, and the browser driver',
  codeLangs: ['ts', 'typescript', 'js'],
  versionSource: { kind: 'package-json', path: 'packages/kizunasync/package.json' },
  supabaseReferenceUrl: 'https://supabase.com/docs/reference/javascript/introduction',
  pages: [
    { slug: 'introduction', title: 'Introduction', kind: 'introduction' },
    { slug: 'installing', title: 'Installing', kind: 'installing' },
    { slug: 'initializing', title: 'Initializing', kind: 'initializing' },
    { slug: 'define-config', title: 'Define config', kind: 'method', section: 'Config' },
    { slug: 'fetch-data', title: 'Fetch data', kind: 'method', section: 'Database' },
    { slug: 'insert-data', title: 'Insert data', kind: 'method', section: 'Database' },
    { slug: 'update-data', title: 'Update data', kind: 'method', section: 'Database' },
    { slug: 'delete-data', title: 'Delete data', kind: 'method', section: 'Database' },
    { slug: 'using-filters', title: 'Using filters', kind: 'guide', section: 'Database' },
    { slug: 'using-transforms', title: 'Using transforms', kind: 'guide', section: 'Database' },
    { slug: 'sync', title: 'Sync', kind: 'method', section: 'Sync' },
    { slug: 'pull-once', title: 'Pull once', kind: 'method', section: 'Sync' },
    { slug: 'push-once', title: 'Push once', kind: 'method', section: 'Sync' },
    { slug: 'set-bucket', title: 'Set bucket', kind: 'method', section: 'Sync' },
    { slug: 'checkpoint', title: 'Checkpoint', kind: 'method', section: 'Sync' },
    { slug: 'outbox-depth', title: 'Outbox depth', kind: 'method', section: 'Sync' },
    { slug: 'sync-health', title: 'Sync health', kind: 'method', section: 'Sync' },
    { slug: 'reset', title: 'Reset', kind: 'method', section: 'Sync' },
    { slug: 'set-access-token', title: 'Set access token', kind: 'method', section: 'Auth session' },
    { slug: 'rejections', title: 'List rejections', kind: 'method', section: 'Rejections' },
    { slug: 'dismiss-rejection', title: 'Dismiss a rejection', kind: 'method', section: 'Rejections' },
    { slug: 'overwrites', title: 'List overwrites', kind: 'method', section: 'Overwrites' },
    { slug: 'dismiss-overwrite', title: 'Dismiss an overwrite', kind: 'method', section: 'Overwrites' },
    { slug: 'on', title: 'Subscribe to events', kind: 'method', section: 'Events' },
    { slug: 'from-file', title: 'Attach a file', kind: 'method', section: 'Attachments' },
    { slug: 'resolve-download', title: 'Resolve a download', kind: 'method', section: 'Attachments' },
    { slug: 'get-status', title: 'Get attachment status', kind: 'method', section: 'Attachments' },
    { slug: 'watch', title: 'Watch an attachment', kind: 'method', section: 'Attachments' },
    { slug: 'attachment-retry', title: 'Retry an attachment', kind: 'method', section: 'Attachments' },
    { slug: 'attachment-cancel', title: 'Cancel an attachment', kind: 'method', section: 'Attachments' },
    { slug: 'attachment-remove', title: 'Remove an attachment', kind: 'method', section: 'Attachments' },
    { slug: 'vacuum', title: 'Vacuum attachments', kind: 'method', section: 'Attachments' },
    { slug: 'create-rpc-remote', title: 'Create the RPC remote', kind: 'method', section: 'Supabase adapters' },
    { slug: 'create-supabase-transfer', title: 'Create the Storage transfer', kind: 'method', section: 'Supabase adapters' },
    { slug: 'tus-upload', title: 'Upload with TUS', kind: 'method', section: 'Supabase adapters' },
    { slug: 'create-realtime-wakeup', title: 'Create the Realtime wakeup', kind: 'method', section: 'Supabase adapters' },
    { slug: 'create-document-foreground', title: 'Create the document foreground', kind: 'method', section: 'Supabase adapters' },
    { slug: 'recover-anonymous-session', title: 'Recover an anonymous session', kind: 'method', section: 'Supabase adapters' },
    { slug: 'with-deadline', title: 'Wait with a deadline', kind: 'method', section: 'Supabase adapters' },
    { slug: 'create-web-worker-driver', title: 'Open the browser driver', kind: 'method', section: 'Browser driver' },
    { slug: 'create-web-connectivity', title: 'Browser connectivity', kind: 'method', section: 'Browser driver' },
    { slug: 'create-web-file-store', title: 'Browser file store', kind: 'method', section: 'Browser driver' },
    { slug: 'build-integration', title: 'Build integration', kind: 'guide', section: 'Browser driver' },
    { slug: 'inspector', title: 'Inspector', kind: 'guide', section: 'Inspector' },
    { slug: 'types', title: 'Types', kind: 'type', section: 'Types' },
    { slug: 'utilities', title: 'Utilities', kind: 'type', section: 'Types' },
  ],
}
