import type { IReferenceLibrary } from '../reference-registry'

// MARK: - Swift client reference tree

export const SWIFT: IReferenceLibrary = {
  id: 'swift',
  title: 'Swift',
  packageName: 'KizunaSync',
  description:
    'KizunaSyncClient over UniFFI for iOS and macOS apps: typed config, optimistic writes, local queries, sync, rejections, events, and attachments',
  codeLangs: ['swift'],
  versionSource: { kind: 'cargo-workspace', path: 'Cargo.toml' },
  supabaseReferenceUrl: 'https://supabase.com/docs/reference/swift/introduction',
  pages: [
    { slug: 'introduction', title: 'Introduction', kind: 'introduction' },
    { slug: 'installing', title: 'Installing', kind: 'installing' },
    { slug: 'initializing', title: 'Initializing', kind: 'initializing' },
    { slug: 'fetch-data', title: 'Fetch data', kind: 'method', section: 'Database' },
    { slug: 'insert-data', title: 'Insert data', kind: 'method', section: 'Database' },
    { slug: 'update-data', title: 'Update data', kind: 'method', section: 'Database' },
    { slug: 'delete-data', title: 'Delete data', kind: 'method', section: 'Database' },
    { slug: 'apply-where', title: 'Write with filters', kind: 'method', section: 'Database' },
    { slug: 'using-filters', title: 'Using filters', kind: 'guide', section: 'Database' },
    { slug: 'using-transforms', title: 'Using transforms', kind: 'guide', section: 'Database' },
    { slug: 'sync', title: 'Sync', kind: 'method', section: 'Sync' },
    { slug: 'pull-once', title: 'Pull once', kind: 'method', section: 'Sync' },
    { slug: 'push-once', title: 'Push once', kind: 'method', section: 'Sync' },
    { slug: 'set-bucket', title: 'Set bucket', kind: 'method', section: 'Sync' },
    { slug: 'checkpoint', title: 'Checkpoint', kind: 'method', section: 'Sync' },
    { slug: 'outbox-depth', title: 'Outbox depth', kind: 'method', section: 'Sync' },
    { slug: 'reset', title: 'Reset', kind: 'method', section: 'Sync' },
    { slug: 'dispose', title: 'Dispose', kind: 'method', section: 'Sync' },
    { slug: 'set-access-token', title: 'Set access token', kind: 'method', section: 'Auth session' },
    { slug: 'rejections', title: 'List rejections', kind: 'method', section: 'Rejections' },
    { slug: 'dismiss-rejection', title: 'Dismiss a rejection', kind: 'method', section: 'Rejections' },
    { slug: 'overwrites', title: 'List overwrites', kind: 'method', section: 'Rejections' },
    { slug: 'dismiss-overwrite', title: 'Dismiss an overwrite', kind: 'method', section: 'Rejections' },
    { slug: 'on', title: 'Subscribe to events', kind: 'method', section: 'Events' },
    { slug: 'from-file', title: 'Attach a file', kind: 'method', section: 'Attachments' },
    { slug: 'resolve-download', title: 'Resolve a download', kind: 'method', section: 'Attachments' },
    { slug: 'get-status', title: 'Get attachment status', kind: 'method', section: 'Attachments' },
    { slug: 'watch', title: 'Watch an attachment', kind: 'method', section: 'Attachments' },
    { slug: 'attachment-retry', title: 'Retry an attachment', kind: 'method', section: 'Attachments' },
    { slug: 'attachment-cancel', title: 'Cancel an attachment', kind: 'method', section: 'Attachments' },
    { slug: 'attachment-remove', title: 'Remove an attachment', kind: 'method', section: 'Attachments' },
    { slug: 'vacuum', title: 'Vacuum attachments', kind: 'method', section: 'Attachments' },
    { slug: 'scheduler', title: 'Host scheduler', kind: 'guide', section: 'Scheduler' },
    { slug: 'inspect', title: 'Inspect', kind: 'method', section: 'Inspector' },
    { slug: 'inspector', title: 'Inspector', kind: 'guide', section: 'Inspector' },
    { slug: 'types', title: 'Types', kind: 'type', section: 'Types' },
  ],
}
