//! A decided config → the project-provisioning SQL (the migration that records it).
//!
//! Nothing in the pack knows which tables an app syncs: the pack installs the
//! substrate, and this codegen closes the loop: `init` emits the SQL below as
//! one more migration, so the migration a reviewer reads is what provisions the
//! project's `kizunasync._config` rows.
//!
//! What it emits, per synced table: an idempotent `kizunasync._config` upsert
//! plus the two generic change-capture triggers (drop-then-create, since
//! `CREATE TRIGGER` has no `OR REPLACE`), the seed that queues a changelog
//! entry for every row the table already holds, plus the three `_provisions`
//! rows `kizunasync deprovision` unwinds. Globally: an `update` of the
//! single-row `kizunasync._settings` naming only the columns the run declared,
//! so a knob nobody named keeps whatever the project already carries.
//!
//! Pure: a config in, a SQL string out.

use std::collections::BTreeMap;

use crate::config::{
    BucketSpec, DEFAULT_MIN_SCHEMA_VERSION, KizunaSyncConfig, ProjectSettings, TableConfig,
};
use crate::constants::{
    INTERNAL_CONFIG, INTERNAL_PROVISIONS, INTERNAL_SETTINGS, SCHEMA, TRACKER_CHANGE, TRACKER_DELETE,
};
use crate::db::strip_control_chars;
use crate::proposals::{Bucket, ConflictMode, SyncMode, TableProposal, build_table_config};

/// Semver token written into `_provisions.pack_version` for config-generated
/// rows: this CLI's version.
const PACK_VERSION: &str = crate::VERSION;

/// `conflict`'s documented default (P:verdict-completeness-transforms-and-conflict-rejection), applied when nothing answered one.
const DEFAULT_CONFLICT: ConflictMode = ConflictMode::Arrival;

/// The namespace a synced table lives in. Fixed rather than configurable: the
/// pack's triggers and RPCs address `public.<table>`.
pub const SYNCED_TABLE_SCHEMA: &str = "public";

/// The scheduler the pack ships: the one writer of the three cron jobs, called
/// after any `_settings` write so a customized schedule survives.
const SCHEDULE_JOBS: &str = "_schedule_jobs";

/// Queues a changelog entry for every row a table held before its triggers
/// existed, which no pull would deliver otherwise.
const SEED_CHANGELOG: &str = "_seed_changelog";

/// Rewrites a table's changelog labels from its current bucket column.
const RELABEL_CHANGELOG: &str = "_relabel_changelog";

/// The two change-capture triggers the pack ships, each with the writes it
/// captures. Both are always attached: a synced table without them would drift
/// silently instead of failing.
const TRACKERS: [(&str, &str); 2] = [
    (TRACKER_CHANGE, "after insert or update"),
    (TRACKER_DELETE, "after delete"),
];

const HEADER: &str = "-- Generated by `kizunasync init`. Provisions YOUR synced tables into\n\
                      -- kizunasync._config (+ the change-capture triggers), and whatever project\n\
                      -- settings this run declared into kizunasync._settings. Idempotent: a re-run\n\
                      -- upserts the same rows and re-creates the same triggers (no-op on no change).";

/// Whether a generated migration refuses to apply without `pg_cron`.
///
/// Defaults to [`CronGate::Required`], matching [`CronGate::from_allow_no_cron`]
/// applied to `bool`'s own default (`false`): a caller that builds a
/// [`crate::sync_delta::DeltaInput`] via struct-update syntax without naming
/// `cron` gets the same gate a run that never passed `--allow-no-cron` would.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum CronGate {
    /// `--allow-no-cron`: install anyway; retention runs by hand.
    Optional,
    /// Stop the migration where the extension is absent.
    #[default]
    Required,
}

impl CronGate {
    /// `Optional` when the run passed `--allow-no-cron`, `Required` otherwise:
    /// the one mapping every caller uses, so a flag threaded through `init`
    /// and `sync` always decides the same gate the same way.
    #[must_use]
    pub const fn from_allow_no_cron(allow_no_cron: bool) -> Self {
        if allow_no_cron {
            Self::Optional
        } else {
            Self::Required
        }
    }
}

/// The `pg_cron`-presence gate a [`CronGate::Required`] migration carries: the
/// pack enables the extension the way Supabase documents
/// (<https://supabase.com/docs/guides/cron/install>), and this block stops the
/// migration where that did not take, so nothing is provisioned that nobody
/// reaps. `waiver` ends the hint: the `--allow-no-cron` of the command that
/// emitted the migration, [`INIT_CRON_WAIVER`] or `sync`'s own. It lands
/// inside a quoted literal in a dollar-quoted block, so it carries no `'` and
/// no `$`.
#[must_use]
pub fn pg_cron_gate_sql(waiver: &str) -> String {
    format!(
        "-- pg_cron runs the three retention jobs. The pack enables it the way Supabase\n\
         -- documents (https://supabase.com/docs/guides/cron/install); this block stops the\n\
         -- migration where that did not take, so nothing is provisioned that nobody reaps.\n\
         do $$\n\
         begin\n\
         \x20 if not exists (select 1 from pg_extension where extname = 'pg_cron') then\n\
         \x20   raise exception 'kizunasync: pg_cron is not enabled on this database'\n\
         \x20     using hint = 'Enable it under Integrations > Cron in the Supabase dashboard, or run `create extension pg_cron with schema pg_catalog;` as https://supabase.com/docs/guides/cron/install shows, then rerun. {waiver}';\n\
         \x20 end if;\n\
         end $$;"
    )
}

/// How the gate in an `init` migration ends its hint.
pub const INIT_CRON_WAIVER: &str =
    "`kizunasync init --allow-no-cron` installs without scheduled retention.";

/// The whole config's provisioning SQL: every synced table in name order (the
/// config's tables are already sorted, which is what keeps the emitted migration
/// byte-stable), then the settings the run declared. A run that declared none
/// emits no `_settings` statement at all. `cron` decides whether the migration
/// carries [`pg_cron_gate_sql`] ahead of every table block.
#[must_use]
pub fn render_config_sql(config: &KizunaSyncConfig, cron: CronGate) -> String {
    let mut blocks = vec![HEADER.to_owned(), String::new()];
    if cron == CronGate::Required {
        blocks.push(pg_cron_gate_sql(INIT_CRON_WAIVER));
        blocks.push(String::new());
    }
    for (table, table_config) in &config.tables {
        blocks.push(table_provision_sql(table, table_config));
        blocks.push(String::new());
    }
    if let Some(settings) = config.settings.as_ref().and_then(settings_sql_for) {
        blocks.push(settings);
        blocks.push(String::new());
    }

    blocks.join("\n")
}

/// A resolved table contract, as `defineConfig` would apply it: what sync's
/// delta migration provisions an added table with.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvedTableConfig {
    /// The sync mode.
    pub sync: SyncMode,
    /// The conflict mode.
    pub conflict: ConflictMode,
    /// Server-side loser-value journal (D-conflict-journal-visibility: not on the wire).
    pub conflict_journal: bool,
    /// Whether the pack records one `kizunasync._clients` row per client.
    pub register_clients: bool,
    /// The lowest client schema version this contract is valid for.
    pub min_schema_version: i64,
    /// An answered tombstone retention in days; absent inherits the project's.
    pub tombstone_ttl_days: Option<i64>,
    /// The bucket, when the table has one.
    pub bucket: Option<Bucket>,
    /// The soft-delete column, when the table has one.
    pub soft_delete: Option<String>,
}

impl ResolvedTableConfig {
    /// A proposal (as answered in the wizard, or bare from a flag), resolved
    /// the way the inference resolves it, so what `init` provisions and what
    /// `sync` adds are decided in exactly one place.
    #[must_use]
    pub fn from_proposal(proposal: &TableProposal) -> Self {
        let draft = build_table_config(proposal);

        Self {
            sync: draft.sync,
            conflict: draft.conflict.unwrap_or(DEFAULT_CONFLICT),
            conflict_journal: draft.conflict_journal,
            register_clients: draft.register_clients,
            min_schema_version: draft
                .min_schema_version
                .unwrap_or(DEFAULT_MIN_SCHEMA_VERSION),
            tombstone_ttl_days: draft.tombstone_ttl_days,
            bucket: draft.bucket,
            soft_delete: draft.soft_delete,
        }
    }

    /// The same contract in the shape `kizunasync._config` records.
    #[must_use]
    pub fn as_table_config(&self) -> TableConfig {
        TableConfig {
            sync: self.sync.as_str().to_owned(),
            bucket: self.bucket.as_ref().map(|bucket| BucketSpec {
                column: bucket.column().to_owned(),
            }),
            conflict: Some(self.conflict.as_str().to_owned()),
            conflict_journal: Some(self.conflict_journal),
            soft_delete: self.soft_delete.clone(),
            register_clients: Some(self.register_clients),
            min_schema_version: self.min_schema_version,
            tombstone_ttl_days: self.tombstone_ttl_days,
        }
    }
}

/// The config `init` provisions from what it proposed: every proposal resolved
/// and keyed by table name, plus whatever settings the run declared.
#[must_use]
pub fn config_from_proposals(
    proposals: &[TableProposal],
    settings: Option<ProjectSettings>,
) -> KizunaSyncConfig {
    let tables: BTreeMap<String, TableConfig> = proposals
        .iter()
        .map(|proposal| {
            (
                proposal.table.clone(),
                ResolvedTableConfig::from_proposal(proposal).as_table_config(),
            )
        })
        .collect();

    KizunaSyncConfig { tables, settings }
}

/// One table's provisioning SQL from a resolved contract.
#[must_use]
pub fn table_provision_sql_resolved(table: &str, config: &ResolvedTableConfig) -> String {
    table_provision_sql(table, &config.as_table_config())
}

/// `public."<table>"`: double-quoted so odd names survive.
#[must_use]
pub fn qualified_table(table: &str) -> String {
    format!("{SYNCED_TABLE_SCHEMA}.{}", quote_ident(table))
}

/// The change-capture trigger's fully qualified name.
#[must_use]
pub fn change_trigger_name(table: &str) -> String {
    format!(
        "{SYNCED_TABLE_SCHEMA}.{table}.{}",
        trigger_name(TRACKER_CHANGE)
    )
}

/// The delete-capture trigger's fully qualified name.
#[must_use]
pub fn delete_trigger_name(table: &str) -> String {
    format!(
        "{SYNCED_TABLE_SCHEMA}.{table}.{}",
        trigger_name(TRACKER_DELETE)
    )
}

/// A single-quoted SQL string literal with embedded quotes doubled.
#[must_use]
pub fn sql_string(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

/// One table's `kizunasync._config` upsert, its two change-capture triggers, and
/// the ledger rows that make its teardown exact.
///
/// Public because `kizunasync sync`'s delta migration provisions an added table
/// through the same single owner `init` uses.
#[must_use]
pub fn table_provision_sql(table: &str, config: &TableConfig) -> String {
    let qualified = format!("{SYNCED_TABLE_SCHEMA}.{}", quote_ident(table));
    let mut lines = vec![
        format!(
            "-- {}: config row + change-capture triggers",
            strip_control_chars(table)
        ),
        format!("insert into {SCHEMA}.{INTERNAL_CONFIG} ("),
        "  table_name, sync_mode, bucket_column, soft_delete_column, conflict_mode, conflict_journal, register_clients, tombstone_ttl_days, min_schema_version"
            .to_owned(),
        ")".to_owned(),
        "values (".to_owned(),
        format!(
            "  {}, {}, {}, {}, {}, {}, {}, {}, {}",
            sql_string(table),
            sql_string(&config.sync),
            sql_nullable_string(config.bucket_column()),
            sql_nullable_string(config.soft_delete.as_deref()),
            sql_string(config.conflict()),
            sql_bool(config.conflict_journal()),
            sql_bool(config.register_clients()),
            sql_nullable_number(config.tombstone_ttl_days),
            config.min_schema_version,
        ),
        ")".to_owned(),
        "on conflict (table_name) do update set".to_owned(),
        "  sync_mode = excluded.sync_mode,".to_owned(),
        "  bucket_column = excluded.bucket_column,".to_owned(),
        "  soft_delete_column = excluded.soft_delete_column,".to_owned(),
        "  conflict_mode = excluded.conflict_mode,".to_owned(),
        "  conflict_journal = excluded.conflict_journal,".to_owned(),
        "  register_clients = excluded.register_clients,".to_owned(),
        "  tombstone_ttl_days = excluded.tombstone_ttl_days,".to_owned(),
        "  min_schema_version = excluded.min_schema_version;".to_owned(),
        String::new(),
    ];

    for (tracker, events) in TRACKERS {
        let trigger = trigger_name(tracker);
        lines.push(format!("drop trigger if exists {trigger} on {qualified};"));
        lines.push(format!("create trigger {trigger}"));
        lines.push(format!("  {events} on {qualified}"));
        lines.push(format!(
            "  for each row execute function {SCHEMA}.{tracker}();"
        ));
        lines.push(String::new());
    }
    lines.push("-- queue a changelog entry for every row the table already holds".to_owned());
    lines.push(format!(
        "select {SCHEMA}.{SEED_CHANGELOG}({});",
        sql_string(table)
    ));
    lines.push(String::new());

    // The ledger rows `kizunasync deprovision` unwinds. content_hash is computed by
    // Postgres (md5 of the config triple / of the tracker name) so the recorded
    // value matches what the pack's own seed writes.
    let config_hash = format!(
        "md5({})",
        sql_string(&format!(
            "{table}:{}:{}",
            config.sync,
            config.bucket_column().unwrap_or_default()
        ))
    );
    lines.push("-- ledger the per-app provisioning so deprovision is exact".to_owned());
    lines.push(format!(
        "insert into {SCHEMA}.{INTERNAL_PROVISIONS} (object_kind, object_name, content_hash, pack_version)"
    ));
    lines.push("values".to_owned());
    lines.push(format!(
        "  ('config',  {}, {config_hash}, {}),",
        sql_string(&format!("{SYNCED_TABLE_SCHEMA}.{table}")),
        sql_string(PACK_VERSION)
    ));
    for (index, (tracker, _)) in TRACKERS.iter().enumerate() {
        let separator = if index + 1 == TRACKERS.len() { "" } else { "," };
        lines.push(format!(
            "  ('trigger', {}, md5('{tracker}'), {}){separator}",
            sql_string(&format!(
                "{SYNCED_TABLE_SCHEMA}.{table}.{}",
                trigger_name(tracker)
            )),
            sql_string(PACK_VERSION)
        ));
    }
    lines.push("on conflict (object_kind, object_name) do nothing;".to_owned());

    lines.join("\n")
}

/// The per-table columns one run named, in the shape `kizunasync._config`
/// records them. A column nobody named is `None` and is never written, so
/// changing one option cannot silently reset the other seven.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct DeclaredTableConfig {
    /// `sync_mode`.
    pub sync: Option<SyncMode>,
    /// `bucket_column`.
    pub bucket_column: Option<String>,
    /// `soft_delete_column`.
    pub soft_delete_column: Option<String>,
    /// `conflict_mode`.
    pub conflict: Option<ConflictMode>,
    /// `conflict_journal`.
    pub conflict_journal: Option<bool>,
    /// `register_clients`.
    pub register_clients: Option<bool>,
    /// `min_schema_version`.
    pub min_schema_version: Option<i64>,
    /// `tombstone_ttl_days`.
    pub tombstone_ttl_days: Option<i64>,
}

impl DeclaredTableConfig {
    /// Whether this run named any column at all.
    #[must_use]
    pub fn is_any_set(&self) -> bool {
        !self.assignments().is_empty()
    }

    /// The contract `live` carries once this declaration is written over it:
    /// a named column wins, every other one keeps what the row already holds.
    #[must_use]
    pub fn over(&self, live: &TableConfig) -> TableConfig {
        TableConfig {
            sync: self
                .sync
                .map_or_else(|| live.sync.clone(), |sync| sync.as_str().to_owned()),
            bucket: self
                .bucket_column
                .clone()
                .map(|column| BucketSpec { column })
                .or_else(|| live.bucket.clone()),
            conflict: self
                .conflict
                .map(|conflict| conflict.as_str().to_owned())
                .or_else(|| live.conflict.clone()),
            conflict_journal: self.conflict_journal.or(live.conflict_journal),
            soft_delete: self
                .soft_delete_column
                .clone()
                .or_else(|| live.soft_delete.clone()),
            register_clients: self.register_clients.or(live.register_clients),
            min_schema_version: self.min_schema_version.unwrap_or(live.min_schema_version),
            tombstone_ttl_days: self.tombstone_ttl_days.or(live.tombstone_ttl_days),
        }
    }

    /// One `column = value` per named option, in the order `_config` declares
    /// them, so the same declaration always renders the same bytes. Public
    /// because the plan report names the assignments it is about to write.
    #[must_use]
    pub fn assignments(&self) -> Vec<String> {
        let mut assignments = Vec::new();
        if let Some(sync) = self.sync {
            assignments.push(format!("sync_mode = {}", sql_string(sync.as_str())));
        }
        if let Some(column) = &self.bucket_column {
            assignments.push(format!("bucket_column = {}", sql_string(column)));
        }
        if let Some(column) = &self.soft_delete_column {
            assignments.push(format!("soft_delete_column = {}", sql_string(column)));
        }
        if let Some(conflict) = self.conflict {
            assignments.push(format!("conflict_mode = {}", sql_string(conflict.as_str())));
        }
        if let Some(journal) = self.conflict_journal {
            assignments.push(format!("conflict_journal = {}", sql_bool(journal)));
        }
        if let Some(register) = self.register_clients {
            assignments.push(format!("register_clients = {}", sql_bool(register)));
        }
        for (column, value) in [
            ("tombstone_ttl_days", self.tombstone_ttl_days),
            ("min_schema_version", self.min_schema_version),
        ] {
            if let Some(value) = value {
                assignments.push(format!("{column} = {value}"));
            }
        }

        assignments
    }
}

/// The `kizunasync._config` update for a table that is already synced: only the
/// options this run named, and nothing else. The two change-capture triggers
/// and the three ledger rows are already there and are deliberately untouched,
/// which is what makes this different from provisioning the table again.
///
/// `None` when the run named no option, because there is nothing to write.
#[must_use]
pub fn table_update_sql_for(table: &str, declared: &DeclaredTableConfig) -> Option<String> {
    let assignments = declared.assignments();
    if assignments.is_empty() {
        return None;
    }

    let mut lines = vec![
        format!(
            "-- {}: update the options this run named, leaving the triggers alone",
            strip_control_chars(table)
        ),
        format!("update {SCHEMA}.{INTERNAL_CONFIG} set"),
    ];
    for (index, assignment) in assignments.iter().enumerate() {
        let separator = if index + 1 == assignments.len() {
            ""
        } else {
            ","
        };
        lines.push(format!("  {assignment}{separator}"));
    }
    lines.push(format!("where table_name = {};", sql_string(table)));

    Some(lines.join("\n"))
}

/// The call that relabels `table`'s changelog by its current bucket column,
/// for the delta to run after the `kizunasync._config` update that moves it:
/// until then every label a pull reads names the old column.
#[must_use]
pub fn relabel_changelog_sql(table: &str) -> String {
    [
        "-- relabel the changelog by the new bucket column; tombstones it cannot scope are dropped"
            .to_owned(),
        format!(
            "select {SCHEMA}.{RELABEL_CHANGELOG}({});",
            sql_string(table)
        ),
    ]
    .join("\n")
}

/// The `kizunasync._settings` update, naming only the columns this run
/// declared, and the scheduler call a declared schedule needs. `None` when the
/// run declared nothing: a knob the user did not name is not a knob to write.
///
/// Public because `kizunasync sync` emits the same statement in its delta.
#[must_use]
pub fn settings_sql_for(settings: &ProjectSettings) -> Option<String> {
    let assignments = settings_assignments(settings);
    if assignments.is_empty() {
        return None;
    }

    let mut lines = vec![
        "-- project settings (kizunasync._settings, single row): only what this run declared"
            .to_owned(),
        format!("update {SCHEMA}.{INTERNAL_SETTINGS} set"),
    ];
    for (index, assignment) in assignments.iter().enumerate() {
        let separator = if index + 1 == assignments.len() {
            ""
        } else {
            ","
        };
        lines.push(format!("  {assignment}{separator}"));
    }
    lines.push("where id;".to_owned());
    if settings.declares_a_schedule() {
        lines.push(String::new());
        lines.push("-- the three cron jobs follow the schedules above".to_owned());
        lines.push(format!("select {SCHEMA}.{SCHEDULE_JOBS}();"));
    }

    Some(lines.join("\n"))
}

/// One `column = value` per declared knob, in the order `_settings` declares
/// them, so the same declaration always renders the same bytes.
fn settings_assignments(settings: &ProjectSettings) -> Vec<String> {
    let mut assignments = Vec::new();
    if let Some(size) = settings.max_batch_size {
        assignments.push(format!("max_batch_size = {}", size.as_sql()));
    }
    if let Some(required) = settings.require_atomic {
        assignments.push(format!("require_atomic = {}", sql_bool(required)));
    }
    for (column, schedule) in [
        ("reap_schedule", settings.reap_schedule.as_deref()),
        ("compact_schedule", settings.compact_schedule.as_deref()),
        (
            "client_prune_schedule",
            settings.client_prune_schedule.as_deref(),
        ),
    ] {
        if let Some(schedule) = schedule {
            assignments.push(format!("{column} = {}", sql_string(schedule)));
        }
    }
    for (column, value) in [
        ("client_ttl_days", settings.client_ttl_days),
        ("hlc_max_skew_ms", settings.hlc_max_skew_ms),
        ("tombstone_ttl_days", settings.tombstone_ttl_days),
        ("max_pull_scan", settings.max_pull_scan),
    ] {
        if let Some(value) = value {
            assignments.push(format!("{column} = {value}"));
        }
    }

    assignments
}

/// The trigger's own name: the schema-prefixed tracker, so it cannot collide with
/// a trigger the app owns.
fn trigger_name(tracker: &str) -> String {
    format!("{SCHEMA}_{tracker}")
}

/// A double-quoted identifier, so a reserved word or an odd name survives.
pub(crate) fn quote_ident(ident: &str) -> String {
    format!("\"{}\"", ident.replace('"', "\"\""))
}

/// An optional text column: a quoted literal, or the SQL `null` keyword.
fn sql_nullable_string(value: Option<&str>) -> String {
    value.map_or_else(|| "null".to_owned(), sql_string)
}

/// An optional integer column: the number, or the SQL `null` keyword. A null
/// `tombstone_ttl_days` is how a table says "the project default".
fn sql_nullable_number(value: Option<i64>) -> String {
    value.map_or_else(|| "null".to_owned(), |value| value.to_string())
}

const fn sql_bool(value: bool) -> &'static str {
    if value { "true" } else { "false" }
}

// Test assertions: an unwrap, expect, or panic here reports a broken test,
// not a runtime fault.
#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use crate::VERSION;
    use crate::config::{DEFAULT_REGISTER_CLIENTS, DEFAULT_TOMBSTONE_TTL_DAYS, MaxBatchSize};

    fn table(sync: &str) -> TableConfig {
        TableConfig {
            sync: sync.to_owned(),
            bucket: None,
            conflict: None,
            conflict_journal: None,
            soft_delete: None,
            register_clients: None,
            min_schema_version: DEFAULT_MIN_SCHEMA_VERSION,
            tombstone_ttl_days: None,
        }
    }

    fn config(
        tables: Vec<(&str, TableConfig)>,
        settings: Option<ProjectSettings>,
    ) -> KizunaSyncConfig {
        KizunaSyncConfig {
            tables: tables
                .into_iter()
                .map(|(name, config)| (name.to_owned(), config))
                .collect(),
            settings,
        }
    }

    fn todos_proposal() -> TableProposal {
        TableProposal::derived(
            "todos",
            Some("user_id"),
            "[auto] RLS policy keys on user_id",
        )
    }

    // MARK: - proposal → resolved contract

    #[test]
    fn an_owner_proposal_resolves_to_read_write_plus_its_bucket() {
        let resolved = ResolvedTableConfig::from_proposal(&todos_proposal());

        assert_eq!(resolved.sync, SyncMode::ReadWrite);
        assert_eq!(resolved.bucket, Some(Bucket::ByOwner("user_id".to_owned())));
        assert_eq!(resolved.conflict, ConflictMode::Arrival);
        assert!(!resolved.conflict_journal);
        assert_eq!(resolved.register_clients, DEFAULT_REGISTER_CLIENTS);
        assert_eq!(resolved.min_schema_version, DEFAULT_MIN_SCHEMA_VERSION);
    }

    #[test]
    fn a_bare_proposal_is_pull_only_with_the_arrival_default_and_no_bucket() {
        let resolved =
            ResolvedTableConfig::from_proposal(&TableProposal::derived("notes", None, "[flag]"));

        assert_eq!(resolved.sync, SyncMode::PullOnly);
        assert_eq!(resolved.bucket, None);
        assert_eq!(resolved.conflict, ConflictMode::Arrival);
        assert_eq!(resolved.soft_delete, None);
    }

    #[test]
    fn every_answered_field_survives_the_resolution() {
        let resolved = ResolvedTableConfig::from_proposal(&TableProposal {
            conflict: Some(ConflictMode::Hlc),
            conflict_journal: true,
            register_clients: true,
            min_schema_version: Some(4),
            soft_delete: Some("deleted_at".to_owned()),
            ..todos_proposal()
        });

        assert_eq!(resolved.conflict, ConflictMode::Hlc);
        assert!(resolved.conflict_journal);
        assert!(resolved.register_clients);
        assert_eq!(resolved.min_schema_version, 4);
        assert_eq!(resolved.soft_delete, Some("deleted_at".to_owned()));
    }

    #[test]
    fn a_proposal_list_becomes_the_config_init_provisions() {
        let config = config_from_proposals(
            &[
                todos_proposal(),
                TableProposal::derived("notes", None, "[auto] no owner"),
            ],
            None,
        );

        assert_eq!(config.synced_tables(), ["notes", "todos"]);
        assert!(config.settings.is_none());
        assert_eq!(config.tables["todos"].sync, "read-write");
        assert_eq!(config.tables["todos"].bucket_column(), Some("user_id"));
        assert_eq!(config.tables["notes"].sync, "pull-only");
    }

    #[test]
    fn a_fully_declared_table_renders_the_golden_block() {
        let sql = table_provision_sql(
            "todos",
            &TableConfig {
                bucket: Some(BucketSpec {
                    column: "user_id".to_owned(),
                }),
                conflict: Some("hlc".to_owned()),
                soft_delete: Some("deleted_at".to_owned()),
                register_clients: Some(true),
                tombstone_ttl_days: Some(7),
                ..table("read-write")
            },
        );

        assert_eq!(
            sql,
            [
                "-- todos: config row + change-capture triggers",
                "insert into kizunasync._config (",
                "  table_name, sync_mode, bucket_column, soft_delete_column, conflict_mode, conflict_journal, register_clients, tombstone_ttl_days, min_schema_version",
                ")",
                "values (",
                "  'todos', 'read-write', 'user_id', 'deleted_at', 'hlc', false, true, 7, 1",
                ")",
                "on conflict (table_name) do update set",
                "  sync_mode = excluded.sync_mode,",
                "  bucket_column = excluded.bucket_column,",
                "  soft_delete_column = excluded.soft_delete_column,",
                "  conflict_mode = excluded.conflict_mode,",
                "  conflict_journal = excluded.conflict_journal,",
                "  register_clients = excluded.register_clients,",
                "  tombstone_ttl_days = excluded.tombstone_ttl_days,",
                "  min_schema_version = excluded.min_schema_version;",
                "",
                "drop trigger if exists kizunasync_track_change on public.\"todos\";",
                "create trigger kizunasync_track_change",
                "  after insert or update on public.\"todos\"",
                "  for each row execute function kizunasync.track_change();",
                "",
                "drop trigger if exists kizunasync_track_delete on public.\"todos\";",
                "create trigger kizunasync_track_delete",
                "  after delete on public.\"todos\"",
                "  for each row execute function kizunasync.track_delete();",
                "",
                "-- queue a changelog entry for every row the table already holds",
                "select kizunasync._seed_changelog('todos');",
                "",
                "-- ledger the per-app provisioning so deprovision is exact",
                "insert into kizunasync._provisions (object_kind, object_name, content_hash, pack_version)",
                "values",
                &format!(
                    "  ('config',  'public.todos', md5('todos:read-write:user_id'), '{VERSION}'),"
                ),
                &format!(
                    "  ('trigger', 'public.todos.kizunasync_track_change', md5('track_change'), '{VERSION}'),"
                ),
                &format!(
                    "  ('trigger', 'public.todos.kizunasync_track_delete', md5('track_delete'), '{VERSION}')"
                ),
                "on conflict (object_kind, object_name) do nothing;",
            ]
            .join("\n")
        );
    }

    #[test]
    fn an_undeclared_bucket_and_soft_delete_become_sql_nulls_with_the_default_conflict() {
        let sql = table_provision_sql("notes", &table("pull-only"));

        assert!(
            sql.contains("  'notes', 'pull-only', null, null, 'arrival', false, false, null, 1")
        );
        // An absent bucket still hashes deterministically: as an empty segment.
        assert!(sql.contains("md5('notes:pull-only:')"));
    }

    #[test]
    fn a_declared_conflict_journal_is_provisioned_true() {
        let sql = table_provision_sql(
            "todos",
            &TableConfig {
                conflict_journal: Some(true),
                ..table("read-write")
            },
        );

        assert!(
            sql.contains("  'todos', 'read-write', null, null, 'arrival', true, false, null, 1")
        );
        assert!(sql.contains("  conflict_journal = excluded.conflict_journal,"));
    }

    /// A table that answered no retention of its own writes SQL `null`, which
    /// is how the pack's reaper reads "use the project default".
    #[test]
    fn an_unanswered_retention_is_a_null_not_a_copy_of_the_project_default() {
        let inherited = table_provision_sql("notes", &table("pull-only"));
        let answered = table_provision_sql(
            "notes",
            &TableConfig {
                tombstone_ttl_days: Some(7),
                ..table("pull-only")
            },
        );

        assert!(inherited.contains("'arrival', false, false, null, 1"));
        assert!(answered.contains("'arrival', false, false, 7, 1"));
    }

    /// A fresh table starts at the documented version, and one that carries a
    /// raised version renders that instead.
    #[test]
    fn the_min_schema_version_rendered_is_the_one_the_config_carries() {
        let fresh = table_provision_sql("notes", &table("pull-only"));
        let raised = table_provision_sql(
            "notes",
            &TableConfig {
                min_schema_version: 2,
                ..table("pull-only")
            },
        );

        assert!(fresh.contains("'arrival', false, false, null, 1"));
        assert!(raised.contains("'arrival', false, false, null, 2"));
    }

    #[test]
    fn an_odd_table_name_is_quoted_in_ddl_and_escaped_in_literals() {
        let sql = table_provision_sql("o'clock\"s", &table("pull-only"));

        assert!(sql.contains("on public.\"o'clock\"\"s\";"));
        assert!(sql.contains("'o''clock\"s'"));
        assert!(sql.contains("select kizunasync._seed_changelog('o''clock\"s');"));
    }

    /// Rows a table held before its triggers existed have no changelog entry,
    /// so the seed runs once both triggers are attached.
    #[test]
    fn the_seed_follows_both_triggers_and_precedes_the_ledger_rows() {
        let sql = table_provision_sql("notes", &table("pull-only"));
        let delete_trigger = sql
            .find("for each row execute function kizunasync.track_delete();")
            .unwrap();
        let seed = sql
            .find("select kizunasync._seed_changelog('notes');")
            .unwrap();
        let ledger = sql.find("insert into kizunasync._provisions").unwrap();

        assert!(delete_trigger < seed);
        assert!(seed < ledger);
    }

    // MARK: - the settings statement

    #[test]
    fn a_run_that_declared_nothing_emits_no_settings_statement() {
        assert_eq!(settings_sql_for(&ProjectSettings::default()), None);

        let sql = render_config_sql(
            &config(vec![], Some(ProjectSettings::default())),
            CronGate::Optional,
        );

        assert!(!sql.contains("update kizunasync._settings"));
    }

    #[test]
    fn only_the_declared_columns_are_named_and_no_scheduler_call_follows_them() {
        let sql = settings_sql_for(&ProjectSettings {
            max_batch_size: Some(MaxBatchSize::Mutations(50)),
            require_atomic: Some(true),
            ..ProjectSettings::default()
        })
        .unwrap();

        assert_eq!(
            sql,
            [
                "-- project settings (kizunasync._settings, single row): only what this run declared",
                "update kizunasync._settings set",
                "  max_batch_size = 50,",
                "  require_atomic = true",
                "where id;",
            ]
            .join("\n")
        );
        assert!(!sql.contains("_schedule_jobs"));
        assert!(!sql.contains("reap_schedule"));
        assert!(!sql.contains("insert into"));
    }

    /// Unlimited is a value the column carries, not a column left alone: a run
    /// that says so must write the null, and one that says nothing must not.
    #[test]
    fn an_explicitly_unlimited_batch_size_writes_the_null() {
        let sql = settings_sql_for(&ProjectSettings {
            max_batch_size: Some(MaxBatchSize::Unlimited),
            ..ProjectSettings::default()
        })
        .unwrap();

        assert!(sql.contains("  max_batch_size = null"));
    }

    #[test]
    fn a_declared_schedule_is_followed_by_the_scheduler_call() {
        let sql = settings_sql_for(&ProjectSettings {
            reap_schedule: Some("0 4 * * *".to_owned()),
            ..ProjectSettings::default()
        })
        .unwrap();

        assert!(sql.contains("  reap_schedule = '0 4 * * *'"));
        assert!(
            sql.trim_end()
                .ends_with("select kizunasync._schedule_jobs();")
        );
    }

    #[test]
    fn every_knob_renders_in_the_order_the_settings_row_declares_them() {
        let sql = settings_sql_for(&ProjectSettings {
            max_batch_size: Some(MaxBatchSize::Mutations(1)),
            require_atomic: Some(false),
            reap_schedule: Some("16 3 * * *".to_owned()),
            compact_schedule: Some("47 3 * * *".to_owned()),
            client_prune_schedule: Some("31 3 * * *".to_owned()),
            client_ttl_days: Some(90),
            hlc_max_skew_ms: Some(5000),
            tombstone_ttl_days: Some(30),
            max_pull_scan: Some(2500),
        })
        .unwrap();

        assert!(
            sql.contains(
                &[
                    "update kizunasync._settings set",
                    "  max_batch_size = 1,",
                    "  require_atomic = false,",
                    "  reap_schedule = '16 3 * * *',",
                    "  compact_schedule = '47 3 * * *',",
                    "  client_prune_schedule = '31 3 * * *',",
                    "  client_ttl_days = 90,",
                    "  hlc_max_skew_ms = 5000,",
                    "  tombstone_ttl_days = 30,",
                    "  max_pull_scan = 2500",
                    "where id;",
                ]
                .join("\n")
            )
        );
    }

    #[test]
    fn the_whole_migration_carries_the_header_every_table_and_the_declared_settings() {
        let sql = render_config_sql(
            &config(
                vec![
                    ("todos", table("read-write")),
                    ("notes", table("pull-only")),
                ],
                Some(ProjectSettings {
                    require_atomic: Some(true),
                    ..ProjectSettings::default()
                }),
            ),
            CronGate::Optional,
        );

        assert!(sql.starts_with("-- Generated by `kizunasync init`."));
        // Tables are emitted in name order, whatever order the config declared them.
        let notes = sql.find("-- notes:").unwrap();
        let todos = sql.find("-- todos:").unwrap();
        assert!(notes < todos);
        assert!(sql.contains("update kizunasync._settings set"));
        assert!(sql.ends_with(";\n"));
    }

    #[test]
    fn a_config_with_no_tables_and_no_settings_provisions_nothing() {
        let sql = render_config_sql(&config(vec![], None), CronGate::Optional);

        assert!(!sql.contains("insert into kizunasync._config"));
        assert!(!sql.contains("update kizunasync._settings"));
    }

    #[test]
    fn the_render_is_byte_stable_across_runs() {
        let declared = || {
            config(
                vec![(
                    "todos",
                    TableConfig {
                        bucket: Some(BucketSpec {
                            column: "user_id".to_owned(),
                        }),
                        tombstone_ttl_days: Some(DEFAULT_TOMBSTONE_TTL_DAYS),
                        ..table("read-write")
                    },
                )],
                Some(ProjectSettings::pack_defaults()),
            )
        };

        assert_eq!(
            render_config_sql(&declared(), CronGate::Optional),
            render_config_sql(&declared(), CronGate::Optional)
        );
    }

    // MARK: - the pg_cron gate

    #[test]
    fn a_required_gate_precedes_the_first_upsert() {
        let sql = render_config_sql(
            &config(vec![("todos", table("read-write"))], None),
            CronGate::Required,
        );

        assert!(sql.contains("pg_cron is not enabled"));
        let gate = sql.find("pg_cron is not enabled").unwrap();
        let first_upsert = sql.find("insert into kizunasync._config").unwrap();
        assert!(gate < first_upsert);
        assert!(
            sql.contains(
                "then rerun. `kizunasync init --allow-no-cron` installs without scheduled retention.';"
            ),
            "{sql}"
        );
    }

    #[test]
    fn an_optional_gate_emits_nothing() {
        let sql = render_config_sql(
            &config(vec![("todos", table("read-write"))], None),
            CronGate::Optional,
        );

        assert!(!sql.contains("pg_extension"));
    }
}
