//! The migration `kizunasync sync` emits for a changed table set.
//!
//! `init` provisions a whole config; sync provisions a DELTA. An added table
//! goes through [`crate::config_sql::table_provision_sql`], the same single
//! owner, so it is byte-for-byte what init would have written, ledger rows
//! included. An update that moves a table to another bucket column is
//! followed by [`crate::config_sql::relabel_changelog_sql`], and one that
//! records a new key by [`crate::config_sql::rekey_changelog_sql`]. A removed table
//! is unwound in the mirror image: both change-capture triggers, its
//! `kizunasync._config` row, and the three `kizunasync._provisions` rows that
//! recorded them, so `kizunasync deprovision` is never left holding an entry
//! for a table this run unwound.
//!
//! What removal deliberately does not touch: the changelog and tombstone rows
//! the table already produced. Deleting them would rewrite history other
//! clients may still be reading; retention reaps them on the normal schedule.
//!
//! Pure: contracts and names in, one SQL string out. No fs, no database.

use crate::config::ProjectSettings;
use crate::config_sql::{
    CronGate, DeclaredTableConfig, ResolvedTableConfig, change_trigger_name, delete_trigger_name,
    pg_cron_gate_sql, qualified_table, rekey_changelog_sql, relabel_changelog_sql,
    settings_sql_for, sql_string, table_provision_sql_resolved, table_update_sql_for,
};
use crate::constants::{
    INTERNAL_CONFIG, INTERNAL_PROVISIONS, SCHEMA, TRACKER_CHANGE, TRACKER_DELETE,
};
use crate::db::strip_control_chars;

// MARK: - constants

const HEADER: &str = concat!(
    "-- Generated by `kizunasync sync`. Provisions the tables you added, updates the\n",
    "-- options of the ones already synced, unwinds the ones you removed (config\n",
    "-- row, triggers, ledger rows), and writes the project settings this run\n",
    "-- declared."
);

/// How the gate in a `sync` delta ends its hint: the flag is `sync`'s, and
/// what it waives is a schedule with no `pg_cron` to run it.
const SYNC_CRON_WAIVER: &str =
    "`kizunasync sync --allow-no-cron` writes the schedule without pg_cron to run it.";

// MARK: - public API

/// One added table: its name and the contract to provision it with.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeltaTable {
    /// The table name, as the config declares it.
    pub table: String,
    /// Its resolved contract.
    pub config: ResolvedTableConfig,
}

/// One already-synced table whose options this run names.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeltaUpdate {
    /// The table name, as `kizunasync._config` carries it.
    pub table: String,
    /// The columns the run named, and only those.
    pub declared: DeclaredTableConfig,
    /// Whether the run moves the table to another bucket column, which
    /// relabels its changelog after the update.
    pub relabel: bool,
}

/// The whole change: what to provision and what to unwind.
#[derive(Debug, Clone, Default)]
pub struct DeltaInput {
    /// Tables the run adds and `kizunasync._config` does not carry yet.
    pub added: Vec<DeltaTable>,
    /// Tables the run is already syncing whose options it updates in place.
    pub updated: Vec<DeltaUpdate>,
    /// Tables the run stops syncing.
    pub removed: Vec<String>,
    /// The settings the run declared. `None` (or a declaration naming no
    /// column) leaves `kizunasync._settings` alone, which is what a run that
    /// named no settings flag must do.
    pub settings: Option<ProjectSettings>,
    /// Whether the delta stops without `pg_cron`; only a delta that declares a
    /// schedule has anything to gate.
    pub cron: CronGate,
}

/// The delta as one transaction: either the config rows, triggers, and ledger
/// rows all move together, or none of them do. Added tables are emitted first,
/// then updated ones, then removed ones, each group sorted by name, so the same
/// change always renders the same bytes. `input.cron` gates the transaction on
/// `pg_cron` (via [`crate::config_sql::pg_cron_gate_sql`]) only when the run
/// also declares a schedule: a delta with nothing to schedule has nothing to
/// gate.
#[must_use]
pub fn render_sync_delta_sql(input: &DeltaInput) -> String {
    let mut added: Vec<&DeltaTable> = input.added.iter().collect();
    added.sort_by(|left, right| left.table.cmp(&right.table));
    let mut updated: Vec<&DeltaUpdate> = input.updated.iter().collect();
    updated.sort_by(|left, right| left.table.cmp(&right.table));
    let mut removed: Vec<&String> = input.removed.iter().collect();
    removed.sort();

    let mut blocks = vec![
        HEADER.to_owned(),
        String::new(),
        "begin;".to_owned(),
        String::new(),
    ];
    if input.cron == CronGate::Required
        && input
            .settings
            .as_ref()
            .is_some_and(ProjectSettings::declares_a_schedule)
    {
        blocks.push(pg_cron_gate_sql(SYNC_CRON_WAIVER));
        blocks.push(String::new());
    }
    for entry in added {
        blocks.push(table_provision_sql_resolved(&entry.table, &entry.config));
        blocks.push(String::new());
    }
    for entry in updated {
        if let Some(sql) = table_update_sql_for(&entry.table, &entry.declared) {
            blocks.push(sql);
            blocks.push(String::new());
        }
        if entry.relabel {
            blocks.push(relabel_changelog_sql(&entry.table));
            blocks.push(String::new());
        }
        if entry.declared.key_columns.is_some() {
            blocks.push(rekey_changelog_sql(&entry.table));
            blocks.push(String::new());
        }
    }
    for table in removed {
        blocks.push(table_removal_sql(table));
        blocks.push(String::new());
    }
    if let Some(settings) = input.settings.as_ref().and_then(settings_sql_for) {
        blocks.push(settings);
        blocks.push(String::new());
    }
    blocks.push("commit;".to_owned());
    blocks.push(String::new());

    blocks.join("\n")
}

// MARK: - removal

fn table_removal_sql(table: &str) -> String {
    let qualified = qualified_table(table);

    [
        format!(
            "-- {} unsync: drop the change-capture triggers, the config row, the ledger rows",
            strip_control_chars(table)
        ),
        format!("drop trigger if exists {SCHEMA}_{TRACKER_CHANGE} on {qualified};"),
        format!("drop trigger if exists {SCHEMA}_{TRACKER_DELETE} on {qualified};"),
        String::new(),
        format!(
            "delete from {SCHEMA}.{INTERNAL_CONFIG} where table_name = {};",
            sql_string(table)
        ),
        String::new(),
        format!("delete from {SCHEMA}.{INTERNAL_PROVISIONS}"),
        "where (object_kind, object_name) in (".to_owned(),
        format!("  ('config',  {}),", sql_string(&format!("public.{table}"))),
        format!(
            "  ('trigger', {}),",
            sql_string(&change_trigger_name(table))
        ),
        format!("  ('trigger', {})", sql_string(&delete_trigger_name(table))),
        ");".to_owned(),
    ]
    .join("\n")
}

// Test assertions: an unwrap, expect, or panic here reports a broken test,
// not a runtime fault.
#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use crate::proposals::TableProposal;

    fn todos() -> TableProposal {
        TableProposal::derived(
            "todos",
            Some("user_id"),
            "[auto] RLS policy keys on user_id",
        )
    }

    fn added(tables: &[&str]) -> Vec<DeltaTable> {
        tables
            .iter()
            .map(|table| DeltaTable {
                table: (*table).to_owned(),
                config: ResolvedTableConfig::from_proposal(&TableProposal::derived(
                    table, None, "[flag]",
                )),
            })
            .collect()
    }

    fn delta(input: &DeltaInput) -> String {
        render_sync_delta_sql(input)
    }

    // MARK: - added tables

    #[test]
    fn an_added_table_is_the_same_bytes_the_provisioning_owner_emits() {
        let config = ResolvedTableConfig::from_proposal(&todos());
        let sql = delta(&DeltaInput {
            added: vec![DeltaTable {
                table: "todos".to_owned(),
                config: config.clone(),
            }],
            ..DeltaInput::default()
        });

        assert!(sql.contains(&table_provision_sql_resolved("todos", &config)));
    }

    #[test]
    fn the_whole_delta_is_one_transaction() {
        let sql = delta(&DeltaInput {
            added: added(&["todos"]),
            ..DeltaInput::default()
        });

        assert!(sql.starts_with("-- Generated by `kizunasync sync`"));
        assert!(sql.contains("\nbegin;\n"));
        assert!(sql.trim_end().ends_with("commit;"));
    }

    // MARK: - removed tables

    #[test]
    fn a_removal_drops_both_triggers_then_the_config_row_then_the_ledger_rows() {
        let sql = delta(&DeltaInput {
            removed: vec!["todos".to_owned()],
            ..DeltaInput::default()
        });
        let change = sql
            .find("drop trigger if exists kizunasync_track_change on public.\"todos\";")
            .unwrap();
        let delete = sql
            .find("drop trigger if exists kizunasync_track_delete on public.\"todos\";")
            .unwrap();
        let config = sql
            .find("delete from kizunasync._config where table_name = 'todos';")
            .unwrap();
        let ledger = sql.find("delete from kizunasync._provisions").unwrap();

        assert!(delete > change);
        assert!(config > delete);
        assert!(ledger > config);
    }

    #[test]
    fn the_ledger_delete_names_exactly_the_three_rows_the_insert_wrote() {
        let sql = delta(&DeltaInput {
            removed: vec!["todos".to_owned()],
            ..DeltaInput::default()
        });

        assert!(
            sql.contains(
                &[
                    "delete from kizunasync._provisions",
                    "where (object_kind, object_name) in (",
                    "  ('config',  'public.todos'),",
                    "  ('trigger', 'public.todos.kizunasync_track_change'),",
                    "  ('trigger', 'public.todos.kizunasync_track_delete')",
                    ");",
                ]
                .join("\n")
            )
        );
    }

    #[test]
    fn changelog_and_tombstone_rows_are_deliberately_left_for_retention() {
        let sql = delta(&DeltaInput {
            removed: vec!["todos".to_owned()],
            ..DeltaInput::default()
        });

        assert!(!sql.contains("_changelog"));
        assert!(!sql.contains("_tombstones"));
    }

    // MARK: - determinism and escaping

    #[test]
    fn added_and_removed_are_each_sorted_added_first() {
        let sql = delta(&DeltaInput {
            added: added(&["zebra", "alpha"]),
            removed: vec!["omega".to_owned(), "beta".to_owned()],
            ..DeltaInput::default()
        });
        let alpha = sql.find("'alpha'").unwrap();
        let zebra = sql.find("'zebra'").unwrap();
        let beta = sql.find("table_name = 'beta'").unwrap();
        let omega = sql.find("table_name = 'omega'").unwrap();

        assert!(alpha < zebra);
        assert!(beta < omega);
        assert!(zebra < beta);
    }

    // MARK: - updated tables

    fn updated(table: &str, declared: DeclaredTableConfig) -> Vec<DeltaUpdate> {
        vec![DeltaUpdate {
            table: table.to_owned(),
            declared,
            relabel: false,
        }]
    }

    /// The whole point of an update: the row moves, the triggers and the ledger
    /// rows it already carries do not.
    #[test]
    fn an_update_writes_only_the_named_columns_and_touches_no_trigger() {
        let sql = delta(&DeltaInput {
            updated: updated(
                "todos",
                DeclaredTableConfig {
                    sync: Some(crate::proposals::SyncMode::ReadWrite),
                    register_clients: Some(true),
                    ..DeclaredTableConfig::default()
                },
            ),
            ..DeltaInput::default()
        });

        assert!(
            sql.contains(
                &[
                    "-- todos: update the options this run named, leaving the triggers alone",
                    "update kizunasync._config set",
                    "  sync_mode = 'read-write',",
                    "  register_clients = true",
                    "where table_name = 'todos';",
                ]
                .join("\n")
            )
        );
        assert!(!sql.contains("create trigger"));
        assert!(!sql.contains("drop trigger"));
        assert!(!sql.contains("_provisions"));
        assert!(!sql.contains("insert into kizunasync._config"));
        assert!(!sql.contains("bucket_column"));
    }

    /// The relabel reads `_config.bucket_column`, so it runs after the update
    /// that moves it, inside the same transaction.
    #[test]
    fn a_bucket_column_change_relabels_the_changelog_after_the_update() {
        let sql = delta(&DeltaInput {
            updated: vec![DeltaUpdate {
                table: "todos".to_owned(),
                declared: DeclaredTableConfig {
                    bucket_column: Some("team_id".to_owned()),
                    min_schema_version: Some(2),
                    ..DeclaredTableConfig::default()
                },
                relabel: true,
            }],
            ..DeltaInput::default()
        });
        let update = sql.find("where table_name = 'todos';").unwrap();
        let relabel = sql
            .find("select kizunasync._relabel_changelog('todos');")
            .unwrap();
        let commit = sql.find("commit;").unwrap();

        assert!(update < relabel);
        assert!(relabel < commit);
    }

    /// The re-key seeds the table by `_config.key_columns`, so it runs after
    /// the update that records the new key, and after a relabel the same
    /// update asked for.
    #[test]
    fn a_recorded_key_change_re_keys_the_changelog_after_the_update() {
        let sql = delta(&DeltaInput {
            updated: vec![DeltaUpdate {
                table: "todos".to_owned(),
                declared: DeclaredTableConfig {
                    bucket_column: Some("team_id".to_owned()),
                    min_schema_version: Some(2),
                    key_columns: Some(vec!["hall".to_owned(), "seat".to_owned()]),
                    ..DeclaredTableConfig::default()
                },
                relabel: true,
            }],
            ..DeltaInput::default()
        });
        let update = sql
            .find("  key_columns = '{hall,seat}'\nwhere table_name = 'todos';")
            .unwrap_or_else(|| panic!("{sql}"));
        let relabel = sql
            .find("select kizunasync._relabel_changelog('todos');")
            .unwrap();
        let rekey = sql
            .find("select kizunasync._rekey_changelog('todos');")
            .unwrap();
        let commit = sql.find("commit;").unwrap();

        assert!(
            update < relabel && relabel < rekey && rekey < commit,
            "{sql}"
        );
    }

    #[test]
    fn an_update_that_keeps_the_bucket_column_relabels_nothing() {
        let sql = delta(&DeltaInput {
            updated: updated(
                "todos",
                DeclaredTableConfig {
                    register_clients: Some(true),
                    ..DeclaredTableConfig::default()
                },
            ),
            ..DeltaInput::default()
        });

        assert!(!sql.contains("_relabel_changelog"));
        assert!(!sql.contains("_rekey_changelog"));
    }

    #[test]
    fn an_added_table_is_seeded_inside_the_transaction() {
        let sql = delta(&DeltaInput {
            added: added(&["widgets"]),
            ..DeltaInput::default()
        });
        let begin = sql.find("begin;").unwrap();
        let seed = sql
            .find("select kizunasync._seed_changelog('widgets');")
            .unwrap();
        let commit = sql.find("commit;").unwrap();

        assert!(begin < seed);
        assert!(seed < commit);
    }

    #[test]
    fn an_update_that_names_nothing_renders_no_statement() {
        let sql = delta(&DeltaInput {
            updated: updated("todos", DeclaredTableConfig::default()),
            ..DeltaInput::default()
        });

        assert!(!sql.contains("update kizunasync._config"));
    }

    #[test]
    fn updates_are_sorted_and_sit_between_the_added_and_the_removed_tables() {
        let mut both = updated(
            "zebra",
            DeclaredTableConfig {
                min_schema_version: Some(2),
                ..DeclaredTableConfig::default()
            },
        );
        both.push(DeltaUpdate {
            table: "beta".to_owned(),
            declared: DeclaredTableConfig {
                min_schema_version: Some(3),
                ..DeclaredTableConfig::default()
            },
            relabel: false,
        });
        let sql = delta(&DeltaInput {
            added: added(&["alpha"]),
            updated: both,
            removed: vec!["omega".to_owned()],
            settings: None,
            cron: CronGate::Required,
        });
        let alpha = sql.find("'alpha'").unwrap();
        let beta = sql.find("where table_name = 'beta';").unwrap();
        let zebra = sql.find("where table_name = 'zebra';").unwrap();
        let omega = sql.find("table_name = 'omega';").unwrap();

        assert!(alpha < beta);
        assert!(beta < zebra);
        assert!(zebra < omega);
    }

    #[test]
    fn an_odd_table_name_is_quoted_as_an_identifier_and_doubled_as_a_literal() {
        let sql = delta(&DeltaInput {
            removed: vec!["it's".to_owned()],
            ..DeltaInput::default()
        });

        assert!(sql.contains("drop trigger if exists kizunasync_track_change on public.\"it's\";"));
        assert!(sql.contains("delete from kizunasync._config where table_name = 'it''s';"));
        assert!(sql.contains("  ('config',  'public.it''s'),"));
    }

    /// A run that named no settings flag leaves `kizunasync._settings` alone;
    /// one that declared a knob carries the update inside the same transaction
    /// as the table work, and names only what it declared.
    #[test]
    fn the_settings_update_appears_only_when_the_run_declared_a_knob() {
        let unchanged = delta(&DeltaInput {
            added: added(&["todos"]),
            ..DeltaInput::default()
        });
        let declared = delta(&DeltaInput {
            added: added(&["todos"]),
            settings: Some(ProjectSettings {
                max_batch_size: Some(crate::config::MaxBatchSize::Mutations(50)),
                require_atomic: Some(true),
                ..ProjectSettings::default()
            }),
            ..DeltaInput::default()
        });

        assert!(!unchanged.contains("kizunasync._settings"));
        assert!(declared.contains("update kizunasync._settings set"));
        assert!(declared.contains("  max_batch_size = 50,"));
        assert!(!declared.contains("reap_schedule"));
        let update = declared.find("update kizunasync._settings").unwrap();
        let commit = declared.find("commit;").unwrap();
        assert!(update < commit, "the settings move with the tables");
    }

    /// A declared schedule brings the scheduler call with it, inside the same
    /// transaction, so the three cron jobs follow the row this delta wrote.
    #[test]
    fn a_declared_schedule_reschedules_the_jobs_in_the_same_transaction() {
        let sql = delta(&DeltaInput {
            settings: Some(ProjectSettings {
                reap_schedule: Some("0 4 * * *".to_owned()),
                ..ProjectSettings::default()
            }),
            ..DeltaInput::default()
        });
        let call = sql.find("select kizunasync._schedule_jobs();").unwrap();
        let commit = sql.find("commit;").unwrap();

        assert!(sql.contains("  reap_schedule = '0 4 * * *'"));
        assert!(call < commit);
    }

    // MARK: - the pg_cron gate

    fn scheduled() -> ProjectSettings {
        ProjectSettings {
            reap_schedule: Some("16 3 * * *".to_owned()),
            ..ProjectSettings::default()
        }
    }

    #[test]
    fn a_required_gate_is_present_when_the_run_declares_a_schedule() {
        let sql = delta(&DeltaInput {
            settings: Some(scheduled()),
            cron: CronGate::Required,
            ..DeltaInput::default()
        });

        assert!(sql.contains("pg_cron is not enabled"));
    }

    /// The hint names the flag of the command that emitted the delta: `sync`
    /// takes `--allow-no-cron` too, and `init` is not what the reader reruns.
    #[test]
    fn the_gates_hint_names_syncs_own_flag() {
        let sql = delta(&DeltaInput {
            settings: Some(scheduled()),
            cron: CronGate::Required,
            ..DeltaInput::default()
        });

        assert!(
            sql.contains(
                "then rerun. `kizunasync sync --allow-no-cron` writes the schedule without pg_cron to run it.';"
            ),
            "{sql}"
        );
        assert!(!sql.contains("kizunasync init"), "{sql}");
    }

    #[test]
    fn an_optional_gate_is_absent_even_with_the_same_schedule() {
        let sql = delta(&DeltaInput {
            settings: Some(scheduled()),
            cron: CronGate::Optional,
            ..DeltaInput::default()
        });

        assert!(!sql.contains("pg_cron is not enabled"));
    }

    #[test]
    fn a_required_gate_is_absent_when_the_run_declares_no_schedule() {
        let sql = delta(&DeltaInput {
            cron: CronGate::Required,
            ..DeltaInput::default()
        });

        assert!(!sql.contains("pg_cron is not enabled"));
    }

    #[test]
    fn an_empty_delta_still_renders_a_valid_empty_transaction() {
        let sql = delta(&DeltaInput::default());

        assert!(sql.contains("begin;"));
        assert!(sql.contains("commit;"));
        assert!(!sql.contains("insert into"));
        assert!(!sql.contains("delete from"));
    }
}
