// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "kizunasync-rn-uniffi.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "NativeRnUniffi.h"

@interface RnUniffi : NSObject <NativeRnUniffiSpec>
#else
#import <React/RCTBridgeModule.h>

@interface RnUniffi : NSObject <RCTBridgeModule>
#endif

@end