-- Generated by `kizunasync init`. Provisions YOUR synced tables into
-- kizunasync._config (+ the change-capture triggers), and whatever project
-- settings this run declared into kizunasync._settings. Idempotent: a re-run
-- upserts the same rows and re-creates the same triggers (no-op on no change).

-- pg_cron runs the three retention jobs. The pack enables it the way Supabase
-- documents (https://supabase.com/docs/guides/cron/install); this block stops the
-- migration where that did not take, so nothing is provisioned that nobody reaps.
do $$
begin
  if not exists (select 1 from pg_extension where extname = 'pg_cron') then
    raise exception 'kizunasync: pg_cron is not enabled on this database'
      using hint = 'Enable it under Integrations > Cron in the Supabase dashboard, or run `create extension pg_cron with schema pg_catalog;` as https://supabase.com/docs/guides/cron/install shows, then rerun. `kizunasync init --allow-no-cron` installs without scheduled retention.';
  end if;
end $$;

-- notes: config row + change-capture triggers
insert into kizunasync._config (
  table_name, sync_mode, bucket_column, soft_delete_column, conflict_mode, conflict_journal, register_clients, tombstone_ttl_days, min_schema_version, key_columns
)
values (
  'notes', 'pull-only', null, null, 'arrival', false, false, null, 1, '{id}'
)
on conflict (table_name) do update set
  sync_mode = excluded.sync_mode,
  bucket_column = excluded.bucket_column,
  soft_delete_column = excluded.soft_delete_column,
  conflict_mode = excluded.conflict_mode,
  conflict_journal = excluded.conflict_journal,
  register_clients = excluded.register_clients,
  tombstone_ttl_days = excluded.tombstone_ttl_days,
  min_schema_version = greatest(kizunasync._config.min_schema_version, excluded.min_schema_version),
  key_columns = excluded.key_columns;

drop trigger if exists kizunasync_track_change on public."notes";
create trigger kizunasync_track_change
  after insert or update on public."notes"
  for each row execute function kizunasync.track_change();

drop trigger if exists kizunasync_track_delete on public."notes";
create trigger kizunasync_track_delete
  after delete on public."notes"
  for each row execute function kizunasync.track_delete();

-- queue a changelog entry for every row the table already holds
select kizunasync._seed_changelog('notes');

-- ledger the per-app provisioning so deprovision is exact
insert into kizunasync._provisions (object_kind, object_name, content_hash, pack_version)
values
  ('config',  'public.notes', md5('notes:pull-only:'), '0.2.6-alpha.3'),
  ('trigger', 'public.notes.kizunasync_track_change', md5('track_change'), '0.2.6-alpha.3'),
  ('trigger', 'public.notes.kizunasync_track_delete', md5('track_delete'), '0.2.6-alpha.3')
on conflict (object_kind, object_name) do nothing;

-- todos: config row + change-capture triggers
insert into kizunasync._config (
  table_name, sync_mode, bucket_column, soft_delete_column, conflict_mode, conflict_journal, register_clients, tombstone_ttl_days, min_schema_version, key_columns
)
values (
  'todos', 'read-write', 'user_id', null, 'arrival', false, false, null, 1, '{id}'
)
on conflict (table_name) do update set
  sync_mode = excluded.sync_mode,
  bucket_column = excluded.bucket_column,
  soft_delete_column = excluded.soft_delete_column,
  conflict_mode = excluded.conflict_mode,
  conflict_journal = excluded.conflict_journal,
  register_clients = excluded.register_clients,
  tombstone_ttl_days = excluded.tombstone_ttl_days,
  min_schema_version = greatest(kizunasync._config.min_schema_version, excluded.min_schema_version),
  key_columns = excluded.key_columns;

drop trigger if exists kizunasync_track_change on public."todos";
create trigger kizunasync_track_change
  after insert or update on public."todos"
  for each row execute function kizunasync.track_change();

drop trigger if exists kizunasync_track_delete on public."todos";
create trigger kizunasync_track_delete
  after delete on public."todos"
  for each row execute function kizunasync.track_delete();

-- queue a changelog entry for every row the table already holds
select kizunasync._seed_changelog('todos');

-- ledger the per-app provisioning so deprovision is exact
insert into kizunasync._provisions (object_kind, object_name, content_hash, pack_version)
values
  ('config',  'public.todos', md5('todos:read-write:user_id'), '0.2.6-alpha.3'),
  ('trigger', 'public.todos.kizunasync_track_change', md5('track_change'), '0.2.6-alpha.3'),
  ('trigger', 'public.todos.kizunasync_track_delete', md5('track_delete'), '0.2.6-alpha.3')
on conflict (object_kind, object_name) do nothing;
