-- Generated by `kizunasync init`. Provisions YOUR synced tables into
-- kizunasync._config (+ the change-capture triggers), and whatever project
-- settings this run declared into kizunasync._settings. Idempotent: a re-run
-- upserts the same rows and re-creates the same triggers (no-op on no change).

-- pg_cron runs the three retention jobs. The pack enables it the way Supabase
-- documents (https://supabase.com/docs/guides/cron/install); this block stops the
-- migration where that did not take, so nothing is provisioned that nobody reaps.
do $$
begin
  if not exists (select 1 from pg_extension where extname = 'pg_cron') then
    raise exception 'kizunasync: pg_cron is not enabled on this database'
      using hint = 'Enable it under Integrations > Cron in the Supabase dashboard, or run `create extension pg_cron with schema pg_catalog;` as https://supabase.com/docs/guides/cron/install shows, then rerun. `kizunasync init --allow-no-cron` installs without scheduled retention.';
  end if;
end $$;

-- project settings (kizunasync._settings, single row): only what this run declared
update kizunasync._settings set
  max_batch_size = 100,
  reap_schedule = '0 4 * * *',
  compact_schedule = '30 4 * * *',
  client_prune_schedule = '45 4 * * *',
  client_ttl_days = 30,
  hlc_max_skew_ms = 2000,
  tombstone_ttl_days = 14,
  max_pull_scan = 2500
where id;

-- the three cron jobs follow the schedules above
select kizunasync._schedule_jobs();

