-- Generated by `kizunasync init`. Provisions YOUR synced tables into
-- kizunasync._config (+ the change-capture triggers), and whatever project
-- settings this run declared into kizunasync._settings. Idempotent: a re-run
-- upserts the same rows and re-creates the same triggers (no-op on no change).

-- notes: config row + change-capture triggers
insert into kizunasync._config (
  table_name, sync_mode, bucket_column, soft_delete_column, conflict_mode, conflict_journal, register_clients, tombstone_ttl_days, min_schema_version, key_columns
)
values (
  'notes', 'pull-only', null, null, 'arrival', false, false, null, 1, '{id}'
)
on conflict (table_name) do update set
  sync_mode = excluded.sync_mode,
  bucket_column = excluded.bucket_column,
  soft_delete_column = excluded.soft_delete_column,
  conflict_mode = excluded.conflict_mode,
  conflict_journal = excluded.conflict_journal,
  register_clients = excluded.register_clients,
  tombstone_ttl_days = excluded.tombstone_ttl_days,
  min_schema_version = greatest(kizunasync._config.min_schema_version, excluded.min_schema_version),
  key_columns = excluded.key_columns;

drop trigger if exists kizunasync_track_change on public."notes";
create trigger kizunasync_track_change
  after insert or update on public."notes"
  for each row execute function kizunasync.track_change();

drop trigger if exists kizunasync_track_delete on public."notes";
create trigger kizunasync_track_delete
  after delete on public."notes"
  for each row execute function kizunasync.track_delete();

-- queue a changelog entry for every row the table already holds
select kizunasync._seed_changelog('notes');

-- ledger the per-app provisioning so deprovision is exact
insert into kizunasync._provisions (object_kind, object_name, content_hash, pack_version)
values
  ('config',  'public.notes', md5('notes:pull-only:'), '0.2.6-alpha.2'),
  ('trigger', 'public.notes.kizunasync_track_change', md5('track_change'), '0.2.6-alpha.2'),
  ('trigger', 'public.notes.kizunasync_track_delete', md5('track_delete'), '0.2.6-alpha.2')
on conflict (object_kind, object_name) do nothing;

-- todos: config row + change-capture triggers
insert into kizunasync._config (
  table_name, sync_mode, bucket_column, soft_delete_column, conflict_mode, conflict_journal, register_clients, tombstone_ttl_days, min_schema_version, key_columns
)
values (
  'todos', 'read-write', 'user_id', 'deleted_at', 'hlc', true, true, 7, 2, '{id}'
)
on conflict (table_name) do update set
  sync_mode = excluded.sync_mode,
  bucket_column = excluded.bucket_column,
  soft_delete_column = excluded.soft_delete_column,
  conflict_mode = excluded.conflict_mode,
  conflict_journal = excluded.conflict_journal,
  register_clients = excluded.register_clients,
  tombstone_ttl_days = excluded.tombstone_ttl_days,
  min_schema_version = greatest(kizunasync._config.min_schema_version, excluded.min_schema_version),
  key_columns = excluded.key_columns;

drop trigger if exists kizunasync_track_change on public."todos";
create trigger kizunasync_track_change
  after insert or update on public."todos"
  for each row execute function kizunasync.track_change();

drop trigger if exists kizunasync_track_delete on public."todos";
create trigger kizunasync_track_delete
  after delete on public."todos"
  for each row execute function kizunasync.track_delete();

-- queue a changelog entry for every row the table already holds
select kizunasync._seed_changelog('todos');

-- ledger the per-app provisioning so deprovision is exact
insert into kizunasync._provisions (object_kind, object_name, content_hash, pack_version)
values
  ('config',  'public.todos', md5('todos:read-write:user_id'), '0.2.6-alpha.2'),
  ('trigger', 'public.todos.kizunasync_track_change', md5('track_change'), '0.2.6-alpha.2'),
  ('trigger', 'public.todos.kizunasync_track_delete', md5('track_delete'), '0.2.6-alpha.2')
on conflict (object_kind, object_name) do nothing;

-- project settings (kizunasync._settings, single row): only what this run declared
update kizunasync._settings set
  max_batch_size = 100,
  reap_schedule = '0 4 * * *',
  compact_schedule = '47 3 * * *',
  client_prune_schedule = '31 3 * * *',
  client_ttl_days = 90,
  hlc_max_skew_ms = 5000,
  tombstone_ttl_days = 30,
  max_pull_scan = 5000
where id;

-- the three cron jobs follow the schedules above
select kizunasync._schedule_jobs();
