-- Generated by `kizunasync sync`. Provisions the tables you added, updates the
-- options of the ones already synced, unwinds the ones you removed (config
-- row, triggers, ledger rows), and writes the project settings this run
-- declared.

begin;

-- pg_cron runs the three retention jobs. The pack enables it the way Supabase
-- documents (https://supabase.com/docs/guides/cron/install); this block stops the
-- migration where that did not take, so nothing is provisioned that nobody reaps.
do $$
begin
  if not exists (select 1 from pg_extension where extname = 'pg_cron') then
    raise exception 'kizunasync: pg_cron is not enabled on this database'
      using hint = 'Enable it under Integrations > Cron in the Supabase dashboard, or run `create extension pg_cron with schema pg_catalog;` as https://supabase.com/docs/guides/cron/install shows, then rerun. `kizunasync sync --allow-no-cron` writes the schedule without pg_cron to run it.';
  end if;
end $$;

-- widgets: config row + change-capture triggers
insert into kizunasync._config (
  table_name, sync_mode, bucket_column, soft_delete_column, conflict_mode, conflict_journal, register_clients, tombstone_ttl_days, min_schema_version, key_columns
)
values (
  'widgets', 'read-write', 'workspace_id', 'deleted_at', 'hlc', true, true, 14, 2, '{id}'
)
on conflict (table_name) do update set
  sync_mode = excluded.sync_mode,
  bucket_column = excluded.bucket_column,
  soft_delete_column = excluded.soft_delete_column,
  conflict_mode = excluded.conflict_mode,
  conflict_journal = excluded.conflict_journal,
  register_clients = excluded.register_clients,
  tombstone_ttl_days = excluded.tombstone_ttl_days,
  min_schema_version = greatest(kizunasync._config.min_schema_version, excluded.min_schema_version),
  key_columns = excluded.key_columns;

drop trigger if exists kizunasync_track_change on public."widgets";
create trigger kizunasync_track_change
  after insert or update on public."widgets"
  for each row execute function kizunasync.track_change();

drop trigger if exists kizunasync_track_delete on public."widgets";
create trigger kizunasync_track_delete
  after delete on public."widgets"
  for each row execute function kizunasync.track_delete();

-- queue a changelog entry for every row the table already holds
select kizunasync._seed_changelog('widgets');

-- ledger the per-app provisioning so deprovision is exact
insert into kizunasync._provisions (object_kind, object_name, content_hash, pack_version)
values
  ('config',  'public.widgets', md5('widgets:read-write:workspace_id'), '0.2.6-alpha.2'),
  ('trigger', 'public.widgets.kizunasync_track_change', md5('track_change'), '0.2.6-alpha.2'),
  ('trigger', 'public.widgets.kizunasync_track_delete', md5('track_delete'), '0.2.6-alpha.2')
on conflict (object_kind, object_name) do nothing;

-- notes unsync: drop the change-capture triggers, the config row, the ledger rows
drop trigger if exists kizunasync_track_change on public."notes";
drop trigger if exists kizunasync_track_delete on public."notes";

delete from kizunasync._config where table_name = 'notes';

delete from kizunasync._provisions
where (object_kind, object_name) in (
  ('config',  'public.notes'),
  ('trigger', 'public.notes.kizunasync_track_change'),
  ('trigger', 'public.notes.kizunasync_track_delete')
);

-- project settings (kizunasync._settings, single row): only what this run declared
update kizunasync._settings set
  max_batch_size = 100,
  reap_schedule = '0 4 * * *',
  compact_schedule = '30 4 * * *',
  client_prune_schedule = '45 4 * * *',
  client_ttl_days = 30,
  hlc_max_skew_ms = 2000,
  max_pull_scan = 2500
where id;

-- the three cron jobs follow the schedules above
select kizunasync._schedule_jobs();

commit;
